FROM openjdk:11-jdk

RUN apt-get update \
	&& apt-get -y install openjfx libswt-gtk-4-jni libswt-gtk-4-java

RUN groupadd -g 1000 developer
RUN useradd -m -u 1000 -g 1000 -s /bin/bash developer

RUN mkdir -p /opt/AxonIvyDesigner && chown -R developer:developer /opt/AxonIvyDesigner

USER developer

VOLUME ["/opt/AxonIvyDesigner", "/opt/workspace"]

EXPOSE 8081

WORKDIR /opt/AxonIvyDesigner

ENTRYPOINT ["/opt/AxonIvyDesigner/Axon.ivy Designer"]
